name: "Yaml Editor"
description: "This is a go github action to edit any yaml provided."
author: "Sotiris Giagkiozis"
inputs:
  myInput:
    description: "Input to use"
    required: true
    default: "world"
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
