name: "Yaml Editor"
description: "This is a go github action to edit any yaml provided."
author: "Sotiris Giagkiozis"
inputs:
  myInput:
    description: "Input to use"
    required: true
    default: "world"
  valueFile:
    required: true
    description: 'the YAML file to be edited'
  propertyPath:
    required: true
    description: 'Property Path - using dot for nesting: e.g. backend.version'
  key:
    required: false
    description: "New property key in case of 'insert' action"
  value:
    required: true
    description: 'New property value'
  action:
    required: true
    description: "Choose one of the following 'insert' to append, 'update' to replace, 'delete' to clear"
    default: 'update'
  branch:
    required: false
    description: 'Branch to commit the change, will be created if not exist'
    default: 'master'
  masterBranchName:
    required: false
    description: 'Branch name of your master'
    default: 'master'
  targetBranch:
    required: false
    description: 'Target Branch for the created PullRequest'
    default: master
  githubAPI:
    required: false
    description: 'GitHub BaseURL'
    default: https://api.github.com
  createPR:
    required: false
    description: 'Create a PullRequest to the configured target branch'
    default: 'false'
  commitChange:
    required: false
    description: 'Commit the change "branch" with the given "message"'
    default: 'true'
  updateFile:
    required: false
    description: 'Update the original File in your workflow'
    default: 'false'
  message:
    required: false
    description: 'Commit message for the value update'
    default: ''
  title:
    required: false
    description: 'Title of the created pull request'
    default: ''
  description:
    required: false
    description: 'Description of the created pull request'
    default: ''
  labels:
    required: false
    description: 'Comma separated list of custom PR labels, e.g. "feature,yaml-updates"'
    default: 'yaml-updates'
  token:
    required: false
    description: 'GitHub AuthToken for Authorization'
    default: ${{ github.token }}
  repository:
    required: false
    description: 'repository to update'
    default: ${{ github.repository }}
  workDir:
    required: false
    description: 'repository workspace location'
    default: .
  commitUserName:
    description: Name used for the commit user
    required: false
    default: GitHub Actions
  commitUserEmail:
    description: Email address used for the commit user
    required: false
    default: actions@github.com
  reviewers:
    description: List of reviewers for the created Pull Request, if enabled
    required: false
    default: ''
  teanReviewers:
    description: List of team reviewers for the created Pull Request, if enabled
    required: false
    default: ''
  assignees:
    description: List of assignees for the created Pull Request, if enabled
    required: false
    default: ''
outputs:
  myOutput:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
