name: "Yaml Editor"
description: "This is a go github action to edit any yaml provided."
author: "Sotiris Giagkiozis"
inputs:
  valueFile:
    required: true
    description: 'the YAML file to be edited'
  parentPath:
    required: true
    description: 'Parent Path - leave empty for root - using dot for nesting: e.g. backend.version'
  key:
    required: false
    description: "The property key to apply any action"
  value:
    required: true
    description: 'New property value'
  action:
    required: true
    description: "Choose one of the following 'upsert' to add or update, 'delete' to clear"
    default: 'upsert'
outputs:
  yamlContent:
    description: "Output from the action"
runs:
  using: "docker"
  image: "Dockerfile"
