name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        with:
          myInput: "world"
          valueFile: "test.yaml"
          propertyPath: "key1"
          key: ""
          value: "test"
          action: "update"
        id: selftest

        # Put your action repo here
        uses: KabamaruS13/yaml-editor@master

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.myOutput }}" == "Hello world"
