name: Integration Test
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Self test
        with:
          valueFile: "test.yaml"
          propertyPath: "key2"
          key: "key7"
          value: "[{\"key71\": \"value75\", \"key72\": \"value76\"}]"
          action: "upsert"
        id: selftest

        # Put your action repo here
        uses: KabamaruS13/yaml-editor@master

      - name: Check outputs
        run: |
          test "${{ steps.selftest.outputs.yamlContent }}" == "key1: value1"
